version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  frontend:
    image: ${REPO}/exchange-frontend
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_SERVER=kafka

  backend:
    image: ${REPO}/exchange-backend
    ports:
      - "8082"
    environment:
      - SPRING_KAFKA_SERVER=kafka
