version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka

  mongodb:
    image: mongo
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data/mongodb:/data/db

  frontend:
    image: ${REPO}/exchange-frontend
    ports:
      - "8081:8081"
    environment:
      - KAFKA_SERVER=kafka

  backend:
    image: ${REPO}/exchange-backend
    ports:
      - "8082"
    environment:
      - KAFKA_SERVER=kafka
      - MONGO_DB_SERVER=mongodb
      - BACKEND_RECORDING=false
      - BACKEND_REPLAY=true