version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 53687091200
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: 60000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka

  mongodb:
    image: mongo
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data/mongodb:/data/db

  frontend:
    image: ${REPO}/exchange-frontend
    ports:
      - "8081:8081"
    environment:
      - KAFKA_SERVER=kafka

  backend:
    image: ${REPO}/exchange-backend
    ports:
      - "8082"
    environment:
      - KAFKA_SERVER=kafka
      - MONGO_DB_SERVER=mongodb
      - BACKEND_RECORDING=false
      - BACKEND_REPLAY=false
      - JAVA_OPTS=-XX:MaxDirectMemorySize=128m