apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  strategy: {}
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: ghcr.io/buildingsoftwareblocks/exchange-admin
          name: admin
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
