kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: local/exchange-admin
          imagePullPolicy: IfNotPresent
          name: admin
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: admin
spec:
  selector:
    app: admin
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
