kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: analysis
  name: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -XX:MaxDirectMemorySize=128m -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
          image: local/exchange-analysis
          imagePullPolicy: IfNotPresent
          name: analysis
          ports:
            - containerPort: 8083

