apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: analysis
  name: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analysis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: analysis
    spec:
      containers:
        - env:
            - name: ADMIN_SERVER
              value: admin
            - name: ANALYSIS_BUYFEES
              value: "0"
            - name: ANALYSIS_SELLFEES
              value: "0"
            - name: ANALYSIS_TRANSPORTFEES
              value: "0.1"
            - name: CONFIG_HOST
              value: config
            - name: JAVA_OPTS
              value: -XX:MaxDirectMemorySize=128m -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
            - name: KAFKA_SERVER
              value: kafka
            - name: LOGSTASH_SERVER
              value: logstash
          image: ghcr.io/buildingsoftwareblocks/exchange-analysis
          name: analysis
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}
