apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: ADMIN_SERVER
              value: admin
            - name: BACKEND_RECORDING
              value: "false"
            - name: BACKEND_REPLAY
              value: "false"
            - name: BACKEND_ZOOKEEPER_HOST
              value: exchange_zk:2181
            - name: CONFIG_HOST
              value: config
            - name: ES_SERVER
              value: elasticsearch
            - name: JAVA_OPTS
              value: -XX:MaxDirectMemorySize=128m -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
            - name: KAFKA_SERVER
              value: kafka
            - name: LOGSTASH_SERVER
              value: logstash
            - name: MONGO_DB_SERVER
              value: mongo
          image: ghcr.io/buildingsoftwareblocks/exchange-backend
          name: backend
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
