kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      volumes:
        - name: config-pv-storage
          persistentVolumeClaim:
            claimName: config-pv-claim
      containers:
        - image: local/exchange-config:latest
          imagePullPolicy: IfNotPresent
          name: config
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: "/configuration"
              name: config-pv-storage

---

kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

