apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - image: ghcr.io/buildingsoftwareblocks/exchange-config
          name: config
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888

