kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  #    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
  #    xpack.monitoring.enabled: true
  #    xpack.monitoring.elasticsearch.username: elastic
  #    xpack.monitoring.elasticsearch.password: changeme
  logstash.conf: |
    input {
      gelf {
        id => "gelf"
        use_udp => false
        use_tcp => true
        port => 5000
      }
    }

    filter {
      prune {
        blacklist_names => [ "source_host", "facility" ]
      }
      mutate {
        # Sets the default value for application, in case someone forgot to set it in their Gelf configuration
        coerce => { "application" => "unknown_application" }
      }
    }

    output {
      # (Un)comment for debugging purposes
      # stdout { codec => rubydebug }
      elasticsearch {
        hosts => ["http://elasticsearch:9200/"]
        index => "app-%{application}-%{+YYYY.MM.dd}"
      }
    }

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - env:
            - name: LS_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
          name: logstash
          image: docker.elastic.co/logstash/logstash:7.17.2
          ports:
            - containerPort: 5000
            - containerPort: 5044
            - containerPort: 9600
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config
            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: config-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf

---

kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: "5000"
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: "5044"
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: "9600"
      port: 9600
      protocol: TCP
      targetPort: 9600