kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # mounting point of docker in WSL mode is /run/desktop/mnt/host
    path: "/run/desktop/mnt/host/e/code/vlog/config-repo"