kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: ghcr.io/buildingsoftwareblocks/exchange-backend
          name: backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config:8888"

---

kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

