name: Delete old container images

on:
  schedule:
    - cron: "0 0 * * 1" # This runs the pipeline every Monday at 00:00
  workflow_dispatch:  # Allow manual triggering

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old released images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.REPO_PAT }}
          image-names: "exchange-backend"
          cut-off: 4w
          image-tags: "!test* !main* !v* !latest 202*"
          keep-n-most-recent: 5

