name: Delete old container images

on:
  workflow_dispatch:

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old released images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: *
          cut-off: One month ago UTC
          image-tags: "!test* !main* !rel* !latest 202*"
          keep-n-most-recent: 5

