# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Feature

on:
  push:
    branches-ignore:
      - 'develop'
      - 'main'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'maven'

      - name: Run formatter
        run: mvn -B process-sources --file pom.xml -P formatter

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatting changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.email "noreply@buildingsoftwareblocks.com"
          git config user.name "buildingSoftwareBlocks"
          git add .
          git commit -m "committed formatting changes"
          git push

      - name: Build with Maven
        run: mvn -B package --file pom.xml
