# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish images to Docker hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package -P docker -Ddocker.repo=$REPO

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker image Backend
        run: docker push $REPO/exchange-backend:latest
      - name: Publish Docker image Frontend
        run: docker push $REPO/exchange-frontend:latest
      - name: Publish Docker image Analysis
        run: docker push $REPO/exchange-analysis:latest