# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Docker images

on:
  push:
    branches: [ develop, main ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Publish to Docker Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B install -P docker -Ddocker.repo=${{ env.REGISTRY }}/${{ github.actor }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker image Config
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/exchange-config:latest
      - name: Publish Docker image Backend
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/exchange-backend:latest
      - name: Publish Docker image Frontend
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/exchange-frontend:latest
      - name: Publish Docker image Analysis
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/exchange-analysis:latest
      - name: Publish Docker image Admin
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/exchange-admin:latest