# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Docker images

on:
  push:
    branches: [ develop ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Publish to Docker Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B install -DskipTests -P docker -Ddocker.repo=${{ env.REGISTRY }}/${{ github.repository }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker image Config
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/exchange-config:latest
      - name: Publish Docker image Backend
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/exchange-backend:latest
      - name: Publish Docker image Frontend
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/exchange-frontend:latest
      - name: Publish Docker image Analysis
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/exchange-analysis:latest