kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/buildingsoftwareblocks/exchange-frontend:latest
          name: frontend
          ports:
            - name: http
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 10
            failureThreshold: 100
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config:8888"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxDirectMemorySize=128m"

---

kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
